apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: users-crud-backend
        name: backend
        ports:
        - containerPort: 3001
        resources: {}
        env:
        - name: MONGO_URI
          value: "mongodb://admin:admin@mongodb-service:27017/app?authSource=admin"
status: {}
