apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  JWT_SECRET: YmFuYW5h # Example encoded value for "banana"
  JWT_EXPIRATION: MWg= # Example encoded value for "1h"
  APT_KEY: S0VZX1dPUkQ= # Example encoded value for "KEY_WORD"
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWluQG1vbmdvZGItc2VydmljZToyNzAxNy9hcHA/YXV0aFNvdXJjZT1hZG1pbg== # Example encoded value for "mongodb://admin:admin@mongodb-service:27017/app?authSource=admin"